###  🧮  Exercice 1: Création de Tensors
1. Créez un tensor 3x3 rempli de la valeur 7 dans TensorFlow, Keras et PyTorch.
2. Créez un tensor 4x2 rempli de valeurs aléatoires uniformément distribuées entre 0 et 1 dans chaque framework.
----

In [16]:
import tensorflow as tf
import torch

# Q1

# pytorch

matrix7 = torch.full((3, 3), 7)
print(matrix7)

# tensorflow

matrix_tensor = tf.constant(7, shape=[3, 3])
print(matrix_tensor)

matrix7_tf = tf.fill([3, 3], 7)
print(matrix7_tf)

# Q2

# pytorch

matrix = torch.rand((4, 2))
print(matrix)

# tensorflow

matrix_tensor = tf.random.uniform([4, 2], 0, 1)
print(matrix_tensor)




tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])
tf.Tensor(
[[7 7 7]
 [7 7 7]
 [7 7 7]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[7 7 7]
 [7 7 7]
 [7 7 7]], shape=(3, 3), dtype=int32)
tensor([[0.2463, 0.5642],
        [0.8946, 0.9163],
        [0.9423, 0.6725],
        [0.2378, 0.6465]])
tf.Tensor(
[[0.26537395 0.6949972 ]
 [0.12125659 0.37909126]
 [0.83984077 0.64232945]
 [0.81592894 0.17307043]], shape=(4, 2), dtype=float32)


### 🧮 Exercice 2: Opérations et Transformations
1. Créez deux matrices 2x2 et calculez leur produit matriciel dans chaque framework.
2. Redimensionnez une matrice 3x4 en un vecteur de 12 éléments dans chaque framework.
3. Concaténez deux vecteurs de taille 5 horizontalement (axis=1) dans chaque framework.
---

In [28]:
import tensorflow as tf
import torch
import random as rd

# Q1 ------------------------------------

# tensorflow

matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 2], [1, 4]])


prod = tf.matmul(matrix1, matrix2)

print(prod.numpy())

# pyTorch

matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 2], [1, 4]])

prod = tf.matmul(matrix1, matrix2)

print(prod.numpy())

# Q2 ------------------------------------

# pyTorch

matrix7 = torch.full((3, 4), 7)
# print(matrix7)
# print(matrix7.shape[0])
matrix_reshaped = torch.reshape(matrix7, (matrix7.shape[0] * matrix7.shape[1],1))
print(matrix_reshaped.numpy())

# tensorflow

matrix7 = tf.fill([3, 4], 7)
# print(matrix7)
# print(matrix7.shape[0])
matrix_reshaped = tf.reshape(matrix7, (matrix7.shape[0] * matrix7.shape[1],1))
print(matrix_reshaped.numpy())

# Q3 ------------------------------------

# tensorflow


matrix1 = tf.constant([ rd.randint(1, 9) for _ in range(5)])
matrix2 = tf.constant([ rd.randint(1, 9) for _ in range(5)])

concated = tf.concat([matrix1, matrix2], axis=0)
print(concated.numpy())

# Pytorch

matrix1 = torch.tensor([ rd.randint(1, 9) for _ in range(5)])
matrix2 = torch.tensor([ rd.randint(1, 9) for _ in range(5)])

concated = torch.cat([matrix1, matrix2], axis=0)
print(concated.numpy())

[[ 7 10]
 [19 22]]
[[ 7 10]
 [19 22]]
[[7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]]
[[7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]]
[4 9 2 5 6 9 4 3 9 2]
[4 6 3 6 1 5 1 9 3 1]


### 🧮  Exercice 3: Manipulation du Shape
1. Créez un tensor 4x3x2 et affichez son shape dans chaque framework.
2. Redimensionnez le tensor précédent en un tensor 2x12 dans chaque framework.
3. Vérifiez que le nombre total d'éléments reste inchangé après le redimensionnement.
---

In [45]:
import tensorflow as tf
import torch

# Q1 -----------------------------

# tensorflow

tensor_tf = tf.constant([
    [[1, 2],[3, 4],[5, 6]],
    [[7, 8],[9, 0],[1, 4]],
    [[9, 5],[3, 4],[7, 8]],
    [[0, 1],[9, 4],[1, 1]]
    ])

print(tensor_tf.numpy())
print(tensor_tf.shape)

# torch

tensor_torch = torch.tensor([
    [[1, 2],[3, 4],[5, 6]],
    [[7, 8],[9, 0],[1, 4]],
    [[9, 5],[3, 4],[7, 8]],
    [[0, 1],[9, 4],[1, 1]]
    ])

print(tensor_torch.numpy())
print(tensor_torch.shape)

# Q2 -----------------------------

# tensorflow

depth = tensor_tf.shape[0]
lignes = tensor_tf.shape[1]
colonnes = tensor_tf.shape[2]

print(depth, lignes, colonnes)

tensor_tf_reshaped = tf.reshape(tensor_tf, (colonnes, depth*lignes))

print(tensor_tf_reshaped.numpy())

# torch

depth = tensor_torch.shape[0]
lignes = tensor_torch.shape[1]
colonnes = tensor_torch.shape[2]

print(depth, lignes, colonnes)

tensor_torch_reshaped = torch.reshape(tensor_torch, (colonnes, depth*lignes))

print(tensor_torch_reshaped.numpy())

# Q3 -----------------------------

# tensorflow

def verifier_nombre(tensor, tensor_reshaped):
    return tf.size(tensor).numpy() == tf.size(tensor_reshaped).numpy()

if verifier_nombre(tensor_tf, tensor_tf_reshaped):
    print("le nombre d'elements de tensor et tensor reshaped sont egeaux ")
else:
    print("il y a difference entre nombre des elements de tensor et tensor reshaped")


print("--------------------------------------------------------------------------")
# torch

def verifier_nombre(tensor, tensor_reshaped):
    return torch.numel(tensor) == torch.numel(tensor_reshaped)

if verifier_nombre(tensor_torch, tensor_torch_reshaped):
    print("le nombre d'elements de tensor et tensor reshaped sont egeaux ")
else:
    print("il y a difference entre nombre des elements de tensor et tensor reshaped")


[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 0]
  [1 4]]

 [[9 5]
  [3 4]
  [7 8]]

 [[0 1]
  [9 4]
  [1 1]]]
(4, 3, 2)
[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 0]
  [1 4]]

 [[9 5]
  [3 4]
  [7 8]]

 [[0 1]
  [9 4]
  [1 1]]]
torch.Size([4, 3, 2])
4 3 2
[[1 2 3 4 5 6 7 8 9 0 1 4]
 [9 5 3 4 7 8 0 1 9 4 1 1]]
4 3 2
[[1 2 3 4 5 6 7 8 9 0 1 4]
 [9 5 3 4 7 8 0 1 9 4 1 1]]
le nombre d'elements de tensor et tensor reshaped sont egeaux 
--------------------------------------------------------------------------
le nombre d'elements de tensor et tensor reshaped sont egeaux 
