## 7-Exercices Supplémentaires
1. Implémentez une fonction qui normalise un tensor (met chaque valeur entre 0 et 1) dans chaque framework.
2. Créez une fonction qui calcule la transposée d'une matrice dans chaque framework.
3. Écrivez une fonction qui calcule la moyenne de tous les éléments d'un tensor dans chaque framework.

In [10]:
import tensorflow as tf
import torch


# Q1 ----------------------------------

# tensorflow
print('tensorflow')

def normalize_tensor_tf(tensor):
    min_val = tf.reduce_min(tensor)
    max_val = tf.reduce_max(tensor)
    return (tensor - min_val) / (max_val - min_val)

tensor_tf = tf.random.uniform((3, 3))

print(normalize_tensor_tf(tensor_tf).numpy())
print()

# torch
print('pytorch')

def normalize_tensor_torch(tensor):
    min_val = torch.min(tensor)
    max_val = torch.max(tensor)
    return (tensor - min_val) / (max_val - min_val)

tensor_torch = torch.rand((3, 3))

print(normalize_tensor_torch(tensor_torch).numpy())
print()

# Q2 ------------------------------------

# tensorflow

def transposer_tf(tensor):
    return tf.transpose(tensor)

print('transposer de matrice par framework tensorflow')
print(transposer_tf(tensor_tf).numpy())
print()

# torch

def transposer_torch(tensor):
    return tensor_torch.T

print('transposer de matrice par framework torch')
print(transposer_torch(tensor_torch).numpy())

# Q3 -----------------------------------------

def mean_tensor_tf(tensor):
    return tf.reduce_mean(tensor)


def mean_tensor_torch(tensor):
    return torch.mean(tensor)

tensor_tf = tf.random.uniform((3, 3))
tensor_torch = torch.rand((3, 3))

print("Moyenne TensorFlow: {:.4f}".format(mean_tensor_tf(tensor_tf).numpy()))
print("Moyenne PyTorch:{:.4f}".format(mean_tensor_torch(tensor_torch).numpy()))

tensorflow
[[0.         0.43181828 0.00985409]
 [0.5601154  0.8785672  0.52404064]
 [0.2129291  1.         0.75373334]]

pytorch
[[1.         0.5651466  0.6097425 ]
 [0.848483   0.         0.8691768 ]
 [0.46275955 0.665181   0.17198859]]

transposer de matrice par framework tensorflow
[[0.12044871 0.5758748  0.29357994]
 [0.47155726 0.83480585 0.933542  ]
 [0.128461   0.54654264 0.73330426]]

transposer de matrice par framework torch
[[0.9840435  0.8776456  0.6067839 ]
 [0.6786819  0.28182614 0.7489278 ]
 [0.7099979  0.89217716 0.4025995 ]]
Moyenne TensorFlow: 0.4361
Moyenne PyTorch:0.5389
