# TP1 : Plateforme et Environnements pour le Deep Learning

# Introduction

Dans ce tutoriel, nous allons explorer les environnements adaptés au Deep Learning, installer et configurer les bibliothèques essentielles sous Anaconda, et apprendre à utiliser Google Colab et Kaggle pour exécuter du code sur GPU. 

Ce TP vous guidera egalement à travers la manipulation de tensors et d'éléments essentiels dans trois frameworks populaires : TensorFlow, Keras et PyTorch. Nous allons résoudre les problèmes suivants :

- Comprendre la création, la manipulation et les opérations fondamentales sur les tensors.
- Identifier les différences de syntaxe et de bibliothèques entre les frameworks.
- Acquérir les compétences nécessaires pour choisir le framework le plus adapté à une tâche donnée.

# Objectifs Pédagogiques

- Comprendre les environnements adaptés au Deep Learning.

- Installer et configurer TensorFlow, Keras et PyTorch sous Anaconda.

- Utiliser Google Colab et Kaggle pour exécuter du code sur GPU.

- Maîtriser la création et l'initialisation des tensors dans TensorFlow, Keras et PyTorch.

- Effectuer des opérations mathématiques et des transformations de base sur les tensors.

- Comprendre et manipuler les dimensions (shape) des tensors.

# Prérequis

📌 Anaconda installé.

📌 Connaissances de base en Python et Jupyter Notebook.

📌 Un compte Google (pour Google Colab) et un compte Kaggle.


# Partie 1 : Installation et Configuration de l’Environnement Local

## 1.1 Installation d'Anaconda

Téléchargez Anaconda : https://www.anaconda.com/download/success

Installez la version correspondant à votre OS.

## 1.2 Création d'un environnement 

Ouvrez Anaconda Prompt et exécutez :

In [4]:
conda create --name deep_env python=3.8
conda activate deep_env

SyntaxError: invalid syntax (3326130870.py, line 1)

## 1.3 Installation des Bibliothèques

Installez TensorFlow, Keras et PyTorch :

In [ ]:
pip install tensorflow keras torch torchvision torchaudio numpy pandas matplotlib seaborn

## 1.4 Vérification de l'Installation

Dans un terminal ou un Notebook Python :

In [ ]:
import tensorflow as tf
import torch
print("TensorFlow version:", tf.__version__)
print("PyTorch version:", torch.__version__)

TensorFlow version: 2.18.0
PyTorch version: 2.6.0+cpu


# Partie 2 :  Exécution sur Google Colab

## 2.1 Ouvrir Google Colab

Accédez à https://colab.research.google.com/

Créez un nouveau notebook.

## 2.2 Activer le GPU

Allez dans Exécution > Modifier le type d’exécution.

Sélectionnez GPU et validez.

## 2.3 Tester TensorFlow et PyTorch sur Colab

Ajoutez cette cellule et exécutez :

In [ ]:
import tensorflow as tf
import torch
print("GPU TensorFlow :", tf.config.list_physical_devices('GPU'))
print("GPU PyTorch :", torch.cuda.is_available())


GPU TensorFlow : []
GPU PyTorch : False


# Partie 3 : Utilisation de Kaggle pour le Deep Learning

## 3.1 Créer un compte Kaggle

Rendez-vous sur https://www.kaggle.com/ et créez un compte.

## 3.2 Ouvrir un Notebook Kaggle

Cliquez sur New Notebook.

Activez le GPU dans les paramètres du Notebook.

## 3.3 Charger un Dataset Kaggle et Tester TensorFlow/PyTorch

Ajoutez cette cellule et exécutez :

In [ ]:
import tensorflow as tf
import torch
import pandas as pd

df = pd.read_csv("/kaggle/input/titanic/train.csv")
print(df.head())


FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/titanic/train.csv'

# Partie 4 : Manipulation des Tenseurs avec TensorFlow, Keras et PyTorch

## Étape 1: Création et Initialisation des Tensors

Cette section explore la création de tensors dans les trois frameworks. Les tensors sont les structures de données fondamentales, peuvent être créés à partir de listes Python, de tableaux NumPy, ou initialisés avec des valeurs spécifiques (zéros, uns, valeurs aléatoires).

### TensorFlow

In [ ]:
import tensorflow as tf
import numpy as np

# Création à partir d'une liste Python
tensor_tf_list = tf.constant([1, 2, 3, 4, 5])
print(f"TensorFlow (List): {tensor_tf_list}")

TensorFlow (List): [1 2 3 4 5]


In [ ]:
# Création à partir d'un tableau NumPy
array_np = np.array([[1, 2], [3, 4]])
tensor_tf_np = tf.constant(array_np)
print(f"TensorFlow (NumPy): {tensor_tf_np}")

TensorFlow (NumPy): [[1 2]
 [3 4]]


In [ ]:
# Initialisation avec des valeurs spécifiques
zeros_tf = tf.zeros((2, 3))
ones_tf = tf.ones((3, 2))
random_tf = tf.random.normal((2, 2))

print(f"TensorFlow (Zeros): {zeros_tf}")
print(f"TensorFlow (Ones): {ones_tf}")
print(f"TensorFlow (Random Normal): {random_tf}")

TensorFlow (Zeros): [[0. 0. 0.]
 [0. 0. 0.]]
TensorFlow (Ones): [[1. 1.]
 [1. 1.]
 [1. 1.]]
TensorFlow (Random Normal): [[ 0.47649166 -0.39970866]
 [-0.6928633  -0.22486426]]


Fonctions importantes (TensorFlow):

- tf.constant(value, dtype=None): Crée un tensor constant à partir d'une valeur (liste, NumPy array, etc.).

- tf.zeros(shape, dtype=tf.float32): Crée un tensor rempli de zéros avec la forme spécifiée.

- tf.ones(shape, dtype=tf.float32): Crée un tensor rempli d'uns avec la forme spécifiée.

- tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32): Crée un tensor rempli de valeurs aléatoires suivant une distribution normale.

### Keras

Bien que Keras soit souvent utilisé comme une API de haut niveau, il utilise TensorFlow comme backend pour les opérations de bas niveau. Nous allons illustrer l'utilisation des tensors directement dans Keras, même si c'est moins courant.

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

# Keras utilise les tensors TensorFlow sous le capot
tensor_keras = tf.constant([6, 7, 8, 9, 10])
print(f"Keras (TensorFlow Tensor): {tensor_keras}")

Keras (TensorFlow Tensor): [ 6  7  8  9 10]


In [ ]:
# Variables Keras (utile pour les paramètres entraînables)
variable_keras = tf.Variable(tf.random.normal((2, 2)))
print(f"Keras Variable: {variable_keras}")

Keras Variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.60380626,  0.8554252 ],
       [-0.20407018, -0.74976176]], dtype=float32)>


Fonctions importantes (Keras):

- tf.Variable(initial_value, trainable=True): Crée une variable (tensor mutable) qui peut être entraînée.

### Pytorch

In [ ]:
import torch
import numpy as np

# Création à partir d'une liste Python
tensor_torch_list = torch.tensor([1, 2, 3, 4, 5])
print(f"PyTorch (List): {tensor_torch_list}")

PyTorch (List): tensor([1, 2, 3, 4, 5])


In [ ]:
# Création à partir d'un tableau NumPy
array_np = np.array([[1, 2], [3, 4]])
tensor_torch_np = torch.tensor(array_np)
print(f"PyTorch (NumPy): {tensor_torch_np}")

PyTorch (NumPy): tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [ ]:
# Initialisation avec des valeurs spécifiques
zeros_torch = torch.zeros((2, 3))
ones_torch = torch.ones((3, 2))
random_torch = torch.randn((2, 2))

print(f"PyTorch (Zeros): {zeros_torch}")
print(f"PyTorch (Ones): {ones_torch}")
print(f"PyTorch (Random Normal): {random_torch}")

PyTorch (Zeros): tensor([[0., 0., 0.],
        [0., 0., 0.]])
PyTorch (Ones): tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
PyTorch (Random Normal): tensor([[ 0.4089, -0.5634],
        [-1.3637,  0.8423]])


Fonctions importantes (PyTorch):

- torch.tensor(data, dtype=None): Crée un tensor à partir de données (liste, NumPy array, etc.).

- torch.zeros(size, dtype=torch.float32): Crée un tensor rempli de zéros avec la taille spécifiée.

- torch.ones(size, dtype=torch.float32): Crée un tensor rempli d'uns avec la taille spécifiée.

- torch.randn(size, dtype=torch.float32): Crée un tensor rempli de valeurs aléatoires suivant une distribution normale.

### Exercice 1: Création de Tensors

1. Créez un tensor 3x3 rempli de la valeur 7 dans TensorFlow, Keras et PyTorch.

2. Créez un tensor 4x2 rempli de valeurs aléatoires uniformément distribuées entre 0 et 1 dans chaque framework.

## Étape 2: Opérations sur les Tensors
Cette section couvre les opérations mathématiques de base sur les tensors, ainsi que le redimensionnement et la concaténation.

### TensorFlow

In [ ]:
import tensorflow as tf

tensor_a_tf = tf.constant([[1, 2], [3, 4]])
print(tensor_a_tf)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
tensor_b_tf = tf.constant([[5, 6], [7, 8]])
print(tensor_b_tf)

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [ ]:
# Addition et Multiplication
add_tf = tf.add(tensor_a_tf, tensor_b_tf)
print(f"TensorFlow (Addition): {add_tf}")

TensorFlow (Addition): [[ 6  8]
 [10 12]]


In [ ]:
multiply_tf = tf.multiply(tensor_a_tf, tensor_b_tf) #Element-wise multiplication
print(f"TensorFlow (Element-wise Multiplication): {multiply_tf}")

TensorFlow (Element-wise Multiplication): [[ 5 12]
 [21 32]]


In [ ]:
# Produit matriciel
matmul_tf = tf.matmul(tensor_a_tf, tensor_b_tf)
print(f"TensorFlow (Matmul): {matmul_tf}")

TensorFlow (Matmul): [[19 22]
 [43 50]]


In [ ]:
# Redimensionnement
reshape_tf = tf.reshape(tensor_a_tf, (4, 1))
print(f"TensorFlow (Reshape): {reshape_tf}")

NameError: name 'tensor_a_tf' is not defined

In [ ]:
# Concaténation
concat_tf = tf.concat([tensor_a_tf, tensor_b_tf], axis=0)  # Concaténation sur les lignes
print(f"TensorFlow (Concatenation): {concat_tf}")

TensorFlow (Concatenation): [[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Keras

In [ ]:
import tensorflow as tf
from tensorflow import keras

# Keras utilise les fonctions TensorFlow
tensor_a_keras = tf.constant([[1, 2], [3, 4]])
tensor_b_keras = tf.constant([[5, 6], [7, 8]])

add_keras = tf.add(tensor_a_keras, tensor_b_keras)
multiply_keras = tf.multiply(tensor_a_keras, tensor_b_keras) #Element-wise multiplication
matmul_keras = tf.matmul(tensor_a_keras, tensor_b_keras)
reshape_keras = tf.reshape(tensor_a_keras, (4, 1))
concat_keras = tf.concat([tensor_a_keras, tensor_b_keras], axis=0)

print(f"Keras (Addition): {add_keras}")
print(f"Keras (Element-wise Multiplication): {multiply_keras}")
print(f"Keras (Matmul): {matmul_keras}")
print(f"Keras (Reshape): {reshape_keras}")
print(f"Keras (Concatenation): {concat_keras}")

Keras (Addition): [[ 6  8]
 [10 12]]
Keras (Element-wise Multiplication): [[ 5 12]
 [21 32]]
Keras (Matmul): [[19 22]
 [43 50]]
Keras (Reshape): [[1]
 [2]
 [3]
 [4]]
Keras (Concatenation): [[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Pytorch

In [ ]:
import torch

tensor_a_torch = torch.tensor([[1, 2], [3, 4]])
print(tensor_a_torch)

tensor([[1, 2],
        [3, 4]])


In [ ]:
tensor_b_torch = torch.tensor([[5, 6], [7, 8]])
print(tensor_b_torch)

tensor([[5, 6],
        [7, 8]])


In [ ]:
# Addition 
add_torch = torch.add(tensor_a_torch, tensor_b_torch)
print(f"PyTorch (Addition): {add_torch}")

PyTorch (Addition): tensor([[ 6,  8],
        [10, 12]])


In [ ]:
# Multiplication
multiply_torch = torch.mul(tensor_a_torch, tensor_b_torch) #Element-wise multiplication
print(f"PyTorch (Element-wise Multiplication): {multiply_torch}")

PyTorch (Element-wise Multiplication): tensor([[ 5, 12],
        [21, 32]])


In [ ]:
# Produit matriciel
matmul_torch = torch.matmul(tensor_a_torch, tensor_b_torch)
print(f"PyTorch (Matmul): {matmul_torch}")

PyTorch (Matmul): tensor([[19, 22],
        [43, 50]])


In [ ]:
# Redimensionnement
reshape_torch = tensor_a_torch.reshape((4, 1))
print(f"PyTorch (Reshape): {reshape_torch}")

PyTorch (Reshape): tensor([[1],
        [2],
        [3],
        [4]])


In [ ]:
# Concaténation
concat_torch = torch.cat([tensor_a_torch, tensor_b_torch], dim=0)  # Concaténation sur les lignes
print(f"PyTorch (Concatenation): {concat_torch}")

PyTorch (Concatenation): tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


### Exercice 2: Opérations et Transformations

1. Créez deux matrices 2x2 et calculez leur produit matriciel dans chaque framework.
2. Redimensionnez une matrice 3x4 en un vecteur de 12 éléments dans chaque framework.
3. Concaténez deux vecteurs de taille 5 horizontalement (axis=1) dans chaque framework.

## Étape 3: Dimensions (Shape) des Tensors
La manipulation des dimensions (shape) est cruciale pour assurer la compatibilité entre les opérations. Cette section montre comment obtenir et modifier le shape d'un tensor.

### TensorFlow

In [ ]:
import tensorflow as tf

tensor_tf = tf.constant([[1, 2, 3], [4, 5, 6]])

# Obtenir le shape
shape_tf = tf.shape(tensor_tf)
print(f"TensorFlow (Shape): {shape_tf}")

# Redimensionner
reshaped_tf = tf.reshape(tensor_tf, (3, 2))
print(f"TensorFlow (Reshaped): {reshaped_tf}")

TensorFlow (Shape): [2 3]
TensorFlow (Reshaped): [[1 2]
 [3 4]
 [5 6]]


### Keras

In [ ]:
import tensorflow as tf
from tensorflow import keras

tensor_keras = tf.constant([[1, 2, 3], [4, 5, 6]])
shape_keras = tf.shape(tensor_keras)
print(f"Keras (Shape): {shape_keras}")

reshaped_keras = tf.reshape(tensor_keras, (3, 2))
print(f"Keras (Reshaped): {reshaped_keras}")

Keras (Shape): [2 3]
Keras (Reshaped): [[1 2]
 [3 4]
 [5 6]]


### PyTorch

In [ ]:
import torch

tensor_torch = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Obtenir le shape
shape_torch = tensor_torch.shape
print(f"PyTorch (Shape): {shape_torch}")

# Redimensionner
reshaped_torch = tensor_torch.reshape((3, 2))
print(f"PyTorch (Reshaped): {reshaped_torch}")

PyTorch (Shape): torch.Size([2, 3])
PyTorch (Reshaped): tensor([[1, 2],
        [3, 4],
        [5, 6]])


### Exercice 3: Manipulation du Shape

1. Créez un tensor 4x3x2 et affichez son shape dans chaque framework.
2. Redimensionnez le tensor précédent en un tensor 2x12 dans chaque framework.
3. Vérifiez que le nombre total d'éléments reste inchangé après le redimensionnement.

# Exercices Supplémentaires

1. Implémentez une fonction qui normalise un tensor (met chaque valeur entre 0 et 1) dans chaque framework.
2. Créez une fonction qui calcule la transposée d'une matrice dans chaque framework.
3. Écrivez une fonction qui calcule la moyenne de tous les éléments d'un tensor dans chaque framework.


# Conclusion

Ce TP a couvert les bases de la manipulation des tensors dans TensorFlow, Keras et PyTorch. Vous avez appris à créer, initialiser, opérer et transformer des tensors. Les exercices vous ont permis de pratiquer ces compétences et d'appréhender les différences entre les frameworks. Ces fondations sont essentielles pour aborder des concepts plus avancés, comme les réseaux de neurones.



# FAQ

# Ressources Supplémentaires

📌 Documentation TensorFlow https://www.tensorflow.org/

📌 Documentation PyTorch https://pytorch.org/

📌 Tutoriels Google Colab https://colab.research.google.com/

📌 Tutoriels Kaggle https://www.kaggle.com/learn