# TP: Fondamentaux des Tensors en Deep Learning (TensorFlow, Keras, PyTorch)



## 1-Introduction au sujet
----------
Dans le domaine du Deep Learning, les tensors sont les structures de données fondamentales. Ce TP vous guidera à travers la manipulation de tensors et d'éléments essentiels dans trois frameworks populaires : TensorFlow, Keras et PyTorch. Nous allons résoudre les problèmes suivants :

Comprendre la création, la manipulation et les opérations fondamentales sur les tensors.
Identifier les différences de syntaxe et de bibliothèques entre les frameworks.
Acquérir les compétences nécessaires pour choisir le framework le plus adapté à une tâche donnée.


![Alt Text](Tensor-Datatype.jpg)

Le code est à écrire en python3 à la suite des questions dans ce fichier. Vous appuierez soit sur le bouton *run cell*, soit sur les touches *Ctrl-Entrée*, à l’intérieur de la zone de saisie, pour lancer l'exécution de vos commandes. Si la commande est en cours d’exécution une étoile apparaît à côté de la zone de saisie de la commande : In [\*]. Une fois le calcul achevé, l'étoile est remplacée par le numéro du run permettant de retrouver par la suite dans quel ordre ont été lancés chaque bloc. à regarder régulièrement la documentation de ces librairies, des exemples d'utilisation accompagnent généralement l'explication de chaque fonction.

## 2-Objectifs Pédagogiques

- Maîtriser la création et l'initialisation des tensors dans TensorFlow, Keras et PyTorch.
- Effectuer des opérations mathématiques et des transformations de base sur les tensors.
- Comprendre et manipuler les dimensions (shape) des tensors.
- Appréhender les différences de syntaxe et de bibliothèques entre les frameworks.
- Être capable de choisir un framework en fonction des besoins d'un projet.

## 3-Prérequis
### Environnement : Anaconda, Google Colab, Kaggle  

Pour travailler efficacement en Deep Learning, plusieurs environnements sont à notre disposition.  

#### 🔹 Anaconda  
Une distribution populaire de Python qui intègre de nombreux outils scientifiques, dont Jupyter Notebook, facilitant l’expérimentation en intelligence artificielle.  
📌 **Téléchargement** : [Anaconda](https://www.anaconda.com/download/success)  

#### 🔹 Google Colab  
Une plateforme cloud qui permet d’exécuter des notebooks Jupyter sans installation locale. Elle offre un accès gratuit à des GPU et TPU, facilitant l'entraînement des modèles de Deep Learning.  
📌 **Accès** : [Google Colab](https://colab.research.google.com/#create=true)  

#### 🔹 Kaggle  
Une plateforme de data science qui propose des notebooks en ligne avec des ressources GPU gratuites. Idéale pour tester des modèles et accéder à des datasets publics.  
📌 **Accès** : [Kaggle](https://www.kaggle.com/code/)  

---

### Plateformes : TensorFlow, Keras, PyTorch  

Plusieurs bibliothèques sont utilisées pour implémenter des réseaux de neurones en Deep Learning :  

#### 🔹 Keras  
Une API haut niveau fonctionnant au-dessus de TensorFlow, facilitant la création et l’entraînement des réseaux de neurones avec une syntaxe intuitive.  
📌 **Plus d’informations** : [Keras](https://keras.io/) 

#### 🔹 TensorFlow  
Développé par Google, TensorFlow est une bibliothèque puissante et optimisée pour le calcul tensoriel et l’apprentissage automatique. Il est souvent utilisé pour des modèles de production à grande échelle.  
📌 **Site officiel** : [TensorFlow](https://www.tensorflow.org/)  
 
#### 🔹 PyTorch  
Développé par Facebook, PyTorch est une alternative flexible et dynamique à TensorFlow. Il est apprécié pour sa facilité d'utilisation et sa compatibilité avec la recherche académique.  
📌 **Site officiel** : [PyTorch](https://pytorch.org/)  


![Alt Text](image.png)

| Caractéristique/Aspect | **Keras**                          | **TensorFlow**                     | **PyTorch**                        |
|------------------------|------------------------------------|------------------------------------|------------------------------------|
| **Utilisation Principale** | Prototypage rapide              | Production & déploiement           | Recherche & expérimentation        |
| **Facilité d'Utilisation** | Très facile                     | Modérée                            | Modérée                            |
| **Type de Graphe**     | Statique                          | Statique (quelques fonctionnalités dynamiques) | Dynamique                          |
| **Flexibilité**        | Faible                            | Élevée                             | Très élevée                        |
| **Débogage**           | Plus difficile                    | Modéré                             | Plus facile                        |
| **Popularité**         | Débutants & prototypage           | Standard de l'industrie            | Milieu académique & recherche      |

## 4-Installation
Commencez par installer les librairies nécessaires. 
--

In [ ]:
!python.exe -m pip install --upgrade pip

#### To install PyTorch,

🔹1 Using pip (Recommended for most users)
Run this in your terminal or command prompt:


In [ ]:
!pip install torch torchvision torchaudio torchviz

🔹 2. Using Conda (for Anaconda users)

conda install pytorch torchvision torchaudio torchviz -c pytorch

#### To install tensorflow,

🔹1 Using pip (Recommended for most users)
Run this in your terminal or command prompt:


In [ ]:
!pip install tensorflow

🔹 2. Using Conda (for Anaconda users)

conda install -c conda-forge tensorflow

```python
# Common imports

In [ ]:
!pip install matplotlib

**download  [graphviz](https://graphviz.gitlab.io/download/)

In [ ]:
!pip install pydot graphviz

## 5-Manipulation des Tenseurs avec TensorFlow, Keras et PyTorch

### Étape 1: Création et Initialisation des Tensors

Cette section explore la création de tensors dans les trois frameworks. Les tensors peuvent être créés à partir de listes Python, de tableaux NumPy, ou initialisés avec des valeurs spécifiques (zéros, uns, valeurs aléatoires).

#### Tensorflow

In [1]:
import tensorflow as tf
import numpy as np

# Création à partir d'une liste Python
tensor_tf_list = tf.constant([1, 2, 3, 4, 5])
print(f"TensorFlow (List): {tensor_tf_list}")

# Création à partir d'un tableau NumPy
array_np = np.array([[1, 2], [3, 4]])
tensor_tf_np = tf.constant(array_np)
print(f"TensorFlow (NumPy): {tensor_tf_np}")

# Initialisation avec des valeurs spécifiques
zeros_tf = tf.zeros((2, 3))
ones_tf = tf.ones((3, 2))
random_tf = tf.random.normal((2, 2))

print(f"TensorFlow (Zeros): {zeros_tf}")
print(f"TensorFlow (Ones): {ones_tf}")
print(f"TensorFlow (Random Normal): {random_tf}")

TensorFlow (List): [1 2 3 4 5]
TensorFlow (NumPy): [[1 2]
 [3 4]]
TensorFlow (Zeros): [[0. 0. 0.]
 [0. 0. 0.]]
TensorFlow (Ones): [[1. 1.]
 [1. 1.]
 [1. 1.]]
TensorFlow (Random Normal): [[-0.6786423 -1.6680684]
 [ 3.0536501  0.7709694]]


### Fonctions importantes (TensorFlow):
- `tf.constant(value, dtype=None)`: Crée un tensor constant à partir d'une valeur (liste, NumPy array, etc.).
- `tf.zeros(shape, dtype=tf.float32)`: Crée un tensor rempli de zéros avec la forme spécifiée.
- `tf.ones(shape, dtype=tf.float32)`: Crée un tensor rempli d'uns avec la forme spécifiée.
- `tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32)`: Crée un tensor rempli de valeurs aléatoires suivant une distribution normale.

#### Keras
Bien que Keras soit souvent utilisé comme une API de haut niveau, il utilise TensorFlow comme backend pour les opérations de bas niveau. Nous allons illustrer l'utilisation des tensors directement dans Keras, même si c'est moins courant.

In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

# Keras utilise les tensors TensorFlow sous le capot
tensor_keras = tf.constant([6, 7, 8, 9, 10])
print(f"Keras (TensorFlow Tensor): {tensor_keras}")

# Variables Keras (utile pour les paramètres entraînables)
variable_keras = tf.Variable(tf.random.normal((2, 2)))
print(f"Keras Variable: {variable_keras}")

Keras (TensorFlow Tensor): [ 6  7  8  9 10]
Keras Variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.45464167, -1.1336206 ],
       [-0.06673642,  1.0425404 ]], dtype=float32)>


##### Fonctions importantes (Keras):
- `tf.Variable(initial_value, trainable=True)`: Crée une variable (tensor mutable) qui peut être entraînée.

#### PyTorch

In [3]:
import torch
import numpy as np

# Création à partir d'une liste Python
tensor_torch_list = torch.tensor([1, 2, 3, 4, 5])
print(f"PyTorch (List): {tensor_torch_list}")

# Création à partir d'un tableau NumPy
array_np = np.array([[1, 2], [3, 4]])
tensor_torch_np = torch.tensor(array_np)
print(f"PyTorch (NumPy): {tensor_torch_np}")

# Initialisation avec des valeurs spécifiques
zeros_torch = torch.zeros((2, 3))
ones_torch = torch.ones((3, 2))
random_torch = torch.randn((2, 2))

print(f"PyTorch (Zeros): {zeros_torch}")
print(f"PyTorch (Ones): {ones_torch}")
print(f"PyTorch (Random Normal): {random_torch}")

PyTorch (List): tensor([1, 2, 3, 4, 5])
PyTorch (NumPy): tensor([[1, 2],
        [3, 4]])
PyTorch (Zeros): tensor([[0., 0., 0.],
        [0., 0., 0.]])
PyTorch (Ones): tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
PyTorch (Random Normal): tensor([[ 0.5327, -0.0092],
        [-0.2087, -1.0452]])


##### Fonctions importantes (PyTorch):
- `torch.tensor(data, dtype=None)`: Crée un tensor à partir de données (liste, NumPy array, etc.).
- `torch.zeros(size, dtype=torch.float32)`: Crée un tensor rempli de zéros avec la taille spécifiée.
- `torch.ones(size, dtype=torch.float32)`: Crée un tensor rempli d'uns avec la taille spécifiée.
- `torch.randn(size, dtype=torch.float32)`: Crée un tensor rempli de valeurs aléatoires suivant une distribution normale.

###  🧮  Exercice 1: Création de Tensors
1. Créez un tensor 3x3 rempli de la valeur 7 dans TensorFlow, Keras et PyTorch.
2. Créez un tensor 4x2 rempli de valeurs aléatoires uniformément distribuées entre 0 et 1 dans chaque framework.
----

In [2]:
import tensorflow as tf
import torch

# Q1
matrix7 = torch.full((3, 3), 7)
print(matrix7)

matrix_tensor = tf.constant(7, shape=[3, 3])
print(matrix_tensor)

matrix7_tf = tf.fill([3, 3], 7)
print(matrix7_tf)
# Q2

matrix = torch.rand((4, 2))
print(matrix)

matrix_tensor = tf.random.uniform([4, 2], 0, 1)
print(matrix_tensor)




tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])
tf.Tensor(
[[7 7 7]
 [7 7 7]
 [7 7 7]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[7 7 7]
 [7 7 7]
 [7 7 7]], shape=(3, 3), dtype=int32)
tensor([[0.4857, 0.0691],
        [0.3319, 0.6614],
        [0.9903, 0.8741],
        [0.5099, 0.0604]])
tf.Tensor(
[[0.66448224 0.98767924]
 [0.7571683  0.49561548]
 [0.4228078  0.7348676 ]
 [0.8905282  0.50530875]], shape=(4, 2), dtype=float32)


### Étape 2: Opérations sur les Tensors

Cette section couvre les opérations mathématiques de base sur les tensors, ainsi que le redimensionnement et la concaténation.

#### Tensorflow

In [7]:
import tensorflow as tf

tensor_a_tf = tf.constant([[1, 2], [3, 4]])
tensor_b_tf = tf.constant([[5, 6], [7, 8]])

# Addition et Multiplication
add_tf = tf.add(tensor_a_tf, tensor_b_tf)
multiply_tf = tf.multiply(tensor_a_tf, tensor_b_tf)  # Element-wise multiplication

# Produit matriciel
matmul_tf = tf.matmul(tensor_a_tf, tensor_b_tf)

# Redimensionnement
reshape_tf = tf.reshape(tensor_a_tf, (4, 1))

# Concaténation
concat_tf = tf.concat([tensor_a_tf, tensor_b_tf], axis=0)  # Concaténation sur les lignes

print(f"TensorFlow (Addition): {add_tf}")
print(f"TensorFlow (Element-wise Multiplication): {multiply_tf}")
print(f"TensorFlow (Matmul): {matmul_tf}")
print(f"TensorFlow (Reshape): {reshape_tf}")
print(f"TensorFlow (Concatenation): {concat_tf}")

TensorFlow (Addition): [[ 6  8]
 [10 12]]
TensorFlow (Element-wise Multiplication): [[ 5 12]
 [21 32]]
TensorFlow (Matmul): [[19 22]
 [43 50]]
TensorFlow (Reshape): [[1]
 [2]
 [3]
 [4]]
TensorFlow (Concatenation): [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Keras

In [5]:
import tensorflow as tf
from tensorflow import keras

# Keras utilise les fonctions TensorFlow
tensor_a_keras = tf.constant([[1, 2], [3, 4]])
tensor_b_keras = tf.constant([[5, 6], [7, 8]])

add_keras = tf.add(tensor_a_keras, tensor_b_keras)
multiply_keras = tf.multiply(tensor_a_keras, tensor_b_keras)  # Element-wise multiplication
matmul_keras = tf.matmul(tensor_a_keras, tensor_b_keras)
reshape_keras = tf.reshape(tensor_a_keras, (4, 1))
concat_keras = tf.concat([tensor_a_keras, tensor_b_keras], axis=0)

print(f"Keras (Addition): {add_keras}")
print(f"Keras (Element-wise Multiplication): {multiply_keras}")
print(f"Keras (Matmul): {matmul_keras}")
print(f"Keras (Reshape): {reshape_keras}")
print(f"Keras (Concatenation): {concat_keras}")

Keras (Addition): [[ 6  8]
 [10 12]]
Keras (Element-wise Multiplication): [[ 5 12]
 [21 32]]
Keras (Matmul): [[19 22]
 [43 50]]
Keras (Reshape): [[1]
 [2]
 [3]
 [4]]
Keras (Concatenation): [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### PyTorch

In [6]:
import torch

tensor_a_torch = torch.tensor([[1, 2], [3, 4]])
tensor_b_torch = torch.tensor([[5, 6], [7, 8]])

# Addition et Multiplication
add_torch = torch.add(tensor_a_torch, tensor_b_torch)
multiply_torch = torch.mul(tensor_a_torch, tensor_b_torch)  # Element-wise multiplication

# Produit matriciel
matmul_torch = torch.matmul(tensor_a_torch, tensor_b_torch)

# Redimensionnement
reshape_torch = tensor_a_torch.reshape((4, 1))

# Concaténation
concat_torch = torch.cat([tensor_a_torch, tensor_b_torch], dim=0)  # Concaténation sur les lignes

print(f"PyTorch (Addition): {add_torch}")
print(f"PyTorch (Element-wise Multiplication): {multiply_torch}")
print(f"PyTorch (Matmul): {matmul_torch}")
print(f"PyTorch (Reshape): {reshape_torch}")
print(f"PyTorch (Concatenation): {concat_torch}")

PyTorch (Addition): tensor([[ 6,  8],
        [10, 12]])
PyTorch (Element-wise Multiplication): tensor([[ 5, 12],
        [21, 32]])
PyTorch (Matmul): tensor([[19, 22],
        [43, 50]])
PyTorch (Reshape): tensor([[1],
        [2],
        [3],
        [4]])
PyTorch (Concatenation): tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


### 🧮 Exercice 2: Opérations et Transformations
1. Créez deux matrices 2x2 et calculez leur produit matriciel dans chaque framework.
2. Redimensionnez une matrice 3x4 en un vecteur de 12 éléments dans chaque framework.
3. Concaténez deux vecteurs de taille 5 horizontalement (axis=1) dans chaque framework.
---

In [ ]:
import tensorflow as tf
import torch

matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 2], [1, 4]])

prod = tf.matmul(matrix1, matrix2)

print(prod)

matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 2], [1, 4]])

prod = tf.matmul(matrix1, matrix2)

print(prod)
# ------------------------------------

matrix7 = torch.full((3, 4), 7)
print(matrix7)
print(matrix7.shape[0])
matrix_reshaped = torch.reshape(matrix7, (matrix7.shape[0] * matrix7.shape[1],1))
print(matrix_reshaped)




tf.Tensor(
[[ 7 10]
 [19 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [19 22]], shape=(2, 2), dtype=int64)
tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])
3
tensor([[7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7]])


### Étape 3: Dimensions (Shape) des Tensors

La manipulation des dimensions (shape) est cruciale pour assurer la compatibilité entre les opérations. Cette section montre comment obtenir et modifier le shape d'un tensor.

#### Tensorflow

In [15]:
import tensorflow as tf

tensor_tf = tf.constant([[1, 2, 3], [4, 5, 6]])

# Obtenir le shape
shape_tf = tf.shape(tensor_tf)
print(f"TensorFlow (Shape): {shape_tf}")

# Redimensionner
reshaped_tf = tf.reshape(tensor_tf, (3, 2))
print(f"TensorFlow (Reshaped): {reshaped_tf}")

TensorFlow (Shape): [2 3]
TensorFlow (Reshaped): [[1 2]
 [3 4]
 [5 6]]


#### Keras

In [16]:
import tensorflow as tf
from tensorflow import keras

tensor_keras = tf.constant([[1, 2, 3], [4, 5, 6]])
shape_keras = tf.shape(tensor_keras)
print(f"Keras (Shape): {shape_keras}")

reshaped_keras = tf.reshape(tensor_keras, (3, 2))
print(f"Keras (Reshaped): {reshaped_keras}")

Keras (Shape): [2 3]
Keras (Reshaped): [[1 2]
 [3 4]
 [5 6]]


#### PyTorch

In [17]:
import torch

tensor_torch = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Obtenir le shape
shape_torch = tensor_torch.shape
print(f"PyTorch (Shape): {shape_torch}")

# Redimensionner
reshaped_torch = tensor_torch.reshape((3, 2))
print(f"PyTorch (Reshaped): {reshaped_torch}")

PyTorch (Shape): torch.Size([2, 3])
PyTorch (Reshaped): tensor([[1, 2],
        [3, 4],
        [5, 6]])


### 🧮  Exercice 3: Manipulation du Shape
1. Créez un tensor 4x3x2 et affichez son shape dans chaque framework.
2. Redimensionnez le tensor précédent en un tensor 2x12 dans chaque framework.
3. Vérifiez que le nombre total d'éléments reste inchangé après le redimensionnement.
---

In [ ]:
import tensorflow as tf


## 6-Conclusion

Ce TP a couvert les bases de la manipulation des tensors dans TensorFlow, Keras et PyTorch. Vous avez appris à créer, initialiser, opérer et transformer des tensors. Les exercices vous ont permis de pratiquer ces compétences et d'appréhender les différences entre les frameworks. Ces fondations sont essentielles pour aborder des concepts plus avancés, comme les réseaux de neurones.

## 7-Exercices Supplémentaires
1. Implémentez une fonction qui normalise un tensor (met chaque valeur entre 0 et 1) dans chaque framework.
2. Créez une fonction qui calcule la transposée d'une matrice dans chaque framework.
3. Écrivez une fonction qui calcule la moyenne de tous les éléments d'un tensor dans chaque framework.

## FAQ

## Ressources Supplémentaires

Langage utilisé:
- Python 3: https://docs.python.org/3/

Librairie keras:
- [Documentation officielle de Keras](https://keras.io/)
- [Tutoriels TensorFlow](https://www.tensorflow.org/tutorials)

Librairie Pytorch:
- PyTorch: https: https://pytorch.org/docs/stable/

Librairie de math:
- Numpy: https://docs.scipy.org/doc/numpy/reference/
- Scipy: https://docs.scipy.org/doc/scipy/reference/

Librairie d'affichage de données:
- Matplotilb: https://matplotlib.org/contents.html
