### Somme factoriel


In [2]:
def factoriel(n):
    if n <= 1:
        return 1
    return n * factoriel(n - 1)

print(factoriel(0))


1


### la complixité de factoriel function est O(n) 

## Somme factoriel

In [6]:
def somme_fact(L):
    if not L:
        return 0
    return factoriel(L[0]) + somme_fact(L[1:])

print(somme_fact([5, 3, 6, 0, 1]))
print(somme_fact([5, 1, 3]))

848
127


In [8]:
import numpy as np
R = [[0,1,1,1,0,0,0,0],[1,0,1,0,1,0,0,0],[1,1,0,1,1,0,0,0],[1,0,1,0,1,0,1,1],[0,1,1,1,0,1,1,0],[0,0,0,0,1,0,1,1],[0,0,0,1,1,1,0,1],[0,0,0,1,0,1,1,0]]
print (np.array(R))


[[0 1 1 1 0 0 0 0]
 [1 0 1 0 1 0 0 0]
 [1 1 0 1 1 0 0 0]
 [1 0 1 0 1 0 1 1]
 [0 1 1 1 0 1 1 0]
 [0 0 0 0 1 0 1 1]
 [0 0 0 1 1 1 0 1]
 [0 0 0 1 0 1 1 0]]


In [15]:
def voisines(i, j, R):
    return R[i][j] == 1
print(voisines(3, 5, R))

False


In [18]:
def liste_voisine(i, R):
    lst = []
    for j in range(len(R[i])):
        if voisines(i, j, R):
            lst.append(j)
    return lst

print(liste_voisine(3, R))

[0, 2, 4, 6, 7]


In [20]:
def degre(i, R):
    return len(liste_voisine(i, R))
print(degre(3, R))

5


In [22]:
def liste_degres(R):
    D = []
    for i in range(len(R)):
        D.append((i, degre(i, R)))
    return D
print(liste_degres(R))

[(0, 3), (1, 3), (2, 4), (3, 5), (4, 5), (5, 3), (6, 4), (7, 3)]


In [25]:
def tri_villes(D):
    for i in range(len(D) - 1):
        max = i
        for j in range(i+1, len(D)):
            if D[i][1] < D[j][1]:
                max = j
        D[i], D[max] = D[max], D[i]
    return D
print(tri_villes(liste_degres(R)))

[(6, 4), (4, 5), (3, 5), (2, 4), (1, 3), (5, 3), (0, 3), (7, 3)]
