# EXERCICE 1

In [31]:

liste = [10, 23, 22, 42, 12, 50, 98, 1, 8, 65, 70]

print("Affichage en colonne :")
# for element in liste:
#     print(element)
print("Affichage en ligne séparée par '/':", "/".join(map(str, liste)))

# max
print(max(liste))
maximum = liste[0]
for element in liste:
    if maximum < element:
        maximum = element
print(maximum)

# min
print(min(liste))
minimum = liste[0]
for element in liste:
    if minimum > element:
        minimum = element
print(minimum)


# multiple de 3
counter = 0
for element in liste:
    if element % 3 == 0:
        counter += 1
print('nombre de multiple par 3 :',counter)

# la somme des elements de la liste
print('somme de liste est :',sum(liste))
somme = 0
for element in liste:
    somme += element
print('la somme de les elements de liste est :',somme)

# la somme des elements pair de la liste
somme = 0
for element in liste:
    if element % 2 == 0:
        somme += element
print(somme)

#calculer le moyenne arithmetique
moyenne = sum(liste)/len(liste)
print(f'{moyenne:.2f}')

# verification
print('verifier que moyenne superieur a 10:', moyenne >= 10)

#calcul la produit de touts les elements
multiplication = 1
for element in liste:
    if element % 2 == 0:
        multiplication *= element
print('produit de touts les elements de la liste :',multiplication)

#produit des elements entre [50, 70]
produit = 1
for element in liste:
    if element <= 70 and element >= 50:
        produit *= element
print(produit)

# l'inverse de la liste
print(liste[::-1])


Affichage en colonne :
Affichage en ligne séparée par '/': 10/23/22/42/12/50/98/1/8/65/70
98
98
1
1
nombre de multiple par 3 : 2
somme de liste est : 401
la somme de les elements de liste est : 401
312
36.45
verifier que moyenne superieur a 10: True
produit de touts les elements de la liste : 304254720000
227500
[70, 65, 8, 1, 98, 50, 12, 42, 22, 23, 10]


In [34]:
import numpy as np
def inverse(liste):
    return liste[::-1]

liste = [1,2,3,4,5,6]
print(inverse(liste))
tableau = np.array(liste)
print(np.flip(tableau))

[6, 5, 4, 3, 2, 1]
[6 5 4 3 2 1]


In [59]:
liste = [10, 23, 22, 42, 12, 50, 98, 1, 8, 66, 70]

print('-'.join(map(str,liste)))

print(sum(1 for element in liste if element % 3 == 0))

iverse_liste = []
for i in range(len(liste) - 1, -1, -1):
    iverse_liste.append(liste[i])
print(iverse_liste)
# print(inverse(liste))

print(liste[::-1])

10-23-22-42-12-50-98-1-8-66-70
3
[70, 66, 8, 1, 98, 50, 12, 42, 22, 23, 10]
[70, 66, 8, 1, 98, 50, 12, 42, 22, 23, 10]
[70, 66, 8, 1, 98, 50, 12, 42, 22, 23, 10]


## EXERCICE 3

In [5]:



T3 = np.random.rand(3, 3, 3)
print(T3)
print(T3[0,0,0])


[[[0.6297088  0.02614993 0.87423241]
  [0.05392065 0.0219703  0.06511041]
  [0.77056199 0.31294485 0.20493128]]

 [[0.1337245  0.67109888 0.91142324]
  [0.27317739 0.01489147 0.6449712 ]
  [0.86318952 0.60362516 0.40086743]]

 [[0.00377264 0.32074601 0.77921344]
  [0.18463498 0.55296367 0.82895256]
  [0.60292344 0.12382476 0.8454632 ]]]
0.6297087972790225


## EXERCICE 4

In [13]:
matrice1 = np.array([
    [7, 2, 6],
    [2, 2, 3],
    [6, 3, 6]
    ])

matrice2 = np.array([
    [7, 0, 0],
    [0, 2, 0],
    [0, 0, 6]
    ])

print('sans utiliser diag')
# sans utiliser diag
def is_diag(m):
    for i in range(len(m)):
        for j in range(len(m[i])):
            if j != i and m[i][j] != 0:
                return False
    return True
print(is_diag(matrice1))
print(is_diag(matrice2))

print('avec utiliser diag')
# avec utiliser diag
def diag_matrice(m):
    diagonale = np.diag(m)
    print('---------------- diagonale ----------------')
    print(diagonale)
    print('------------- diag of diagonale -----------')
    print(np.diag(diagonale))
    print('------------- rest of matrice -------------')
    rest_de_matrice = m - np.diag(diagonale)
    print(rest_de_matrice)
    print('-------------- true or false --------------')
    if np.any(rest_de_matrice != 0):
        return False
    return True

print(diag_matrice(matrice1))
print(diag_matrice(matrice2))


            
                

sans utiliser diag
False
True
avec utiliser diag
---------------- diagonale ----------------
[7 2 6]
------------- diag of diagonale -----------
[[7 0 0]
 [0 2 0]
 [0 0 6]]
------------- rest of matrice -------------
[[0 2 6]
 [2 0 3]
 [6 3 0]]
-------------- true or false --------------
False
---------------- diagonale ----------------
[7 2 6]
------------- diag of diagonale -----------
[[7 0 0]
 [0 2 0]
 [0 0 6]]
------------- rest of matrice -------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]
-------------- true or false --------------
True


## EXERCICE 5


In [32]:
T1 = np.array([i for i in range(51) if i % 2 == 0])
T1 = np.arange(0, 51, 2)
print(T1)

T2 = np.cos(T1 ** 2)

T2 = [float(f'{i:.3f}') for i in T2]
# T2 = [float(f"{np.cos(T1[i]) ** 2:.2f}") for i in range(len(T1))] hadchi khata2

print(T2)

print(min(T2))

print(sum(1 for i in T2 if max(T2) == i))


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
[1.0, -0.654, -0.958, -0.128, 0.392, 0.862, 0.871, 0.342, -0.04, -0.915, -0.525, 0.981, -0.464, -0.849, 0.172, 0.066, 0.987, 0.994, -0.093, 0.424, -0.598, -0.004, 0.712, 0.137, -0.351, 0.76]
-0.958
1


## EXERCICE 6

In [3]:
liste = [1, 2, 3, 2, 1]
liste1 = [1, 2, 3, 2, 2]

def est_symetrique(liste):
    return liste == liste[::-1]
print(est_symetrique(liste))
print(est_symetrique(liste1))

True
False
